### ISSUE TITLE
(Bug) Spawned in enemy grids, and pasted in enemy grids don't auto fire at characters 

### ISSUE THREAD

**Issue by nukeguard** [sstixrud/WeaponCore#174] opened 2020-06-10 10:53 UTC
## Is this a multiplayer or singleplayer bug?
both

## Describe the bug:
turrets with Character as valid target don't auto fire at characters when spawned in or when pasted in as pirates

## Steps To Reproduce:
use any wc enabled weapon mod that has character as a threat target

## Expected behavior:
enemy character seen, shoot enemy character

![image](https://user-images.githubusercontent.com/30876973/84259808-02d67d80-aae7-11ea-9d06-cb9339d6b88e.png)

This is occuring on current Steam version of WC

**Comment by sstixrud** [comment] 2020-06-15 04:41
Should be fixed, please confirm

**Comment by sstixrud** [comment] 2020-06-17 01:40
not a bug, disable all admin settings and it will work as intended.

**Closed by sstixrud** 2020-06-17 01:40 UTC
Labels: Housecleaning (Bug)
