### ISSUE TITLE
Vanilla replacement weapons not firing

### ISSUE THREAD

**Issue by nukeguard** [sstixrud/WeaponCore#148] opened 2020-05-04 21:52 UTC
User: Grant 
Mod: Vanilla Replacement 
-- 
Currently this mod causes gatling turrets and static gatling guns to not fire (not sure if missile turrets and static missile guns are affected). Well, they fire once but won't fire again.

**Comment by nukeguard** [comment] 2020-05-04 21:52
I'll check this on git weapon core, in survival

**Comment by nukeguard** [comment] 2020-05-04 22:18
reloadable rocket launcher is the only one of the weapons that doesn't have click to fire in the list, all weapons work as expected then stop firing even though they are still targeting
![image](https://user-images.githubusercontent.com/30876973/81018998-ac18bc80-8e33-11ea-8801-17098a7a5015.png)

**Comment by nukeguard** [comment] 2020-05-04 22:22
seems gatlings stop firing, new targets missiles will fire, but gatling turrets do not, they shoot once in a while

**Comment by redsleepinggrass** [comment] 2020-05-12 16:41
I am having a very similar issue when the mod is loaded locally or on dedicated servers. Certain weapons seem to load just fine, others are broken. The problem seems to be related to weaponcore not loading on broken weapons, as the weaponcore stats do not show up in the terminal.

Details:
- Small ship gatling gun: non-functional, weaponcore not loaded
- Small ship missile launcher: non-functional, weaponcore not loaded
- Small ship reloadable rocket launcher: functional
- Small ship gatling turret: functional
- Small ship missile turret: functional
- Large ship missile launcher: functional
- Large ship interior turret: functional
- Large ship gatling turret: non-functional, weaponcore not loaded
- Large ship missile turret: non-functional, weaponcore not loaded

I think it is also important to note that an EXACT duplicate of the mod I uploaded to the steam workshop to determine if it had something to do with the way mods are loaded when subscribed to them also produced the same broken results.

Hopefully this is helpful.

**Comment by nukeguard** [comment] 2020-05-17 04:00
I will check these tomorrow with current offline weapon core, and update accordingly if there are issues with it I can fix.

**Comment by sstixrud** [comment] 2020-05-21 03:44
fixed

**Closed by sstixrud** 2020-05-21 03:44 UTC
Labels: Housecleaning (Bug)
