### ISSUE TITLE
PB GetSortedThreats frequently returns MyDetectedEntityType.Unknown for Grid Targets

### ISSUE THREAD

**Issue by keleios** [sstixrud/WeaponCore#524] opened 2022-10-21 23:37 UTC
It appears that this if statement fails in many situations:
https://github.com/sstixrud/WeaponCore/blob/a46f015f8130bacd98c7e27b5ddf29a514fc7750/Data/Scripts/CoreSystems/Api/ApiBackend.cs#L392

Resulting in the relation & type not being set when it returns a result:
https://github.com/sstixrud/WeaponCore/blob/a46f015f8130bacd98c7e27b5ddf29a514fc7750/Data/Scripts/CoreSystems/Api/ApiBackend.cs#L423

After reading it for a bit, the type can be set for Small and Large grid via topTarget as MyCubeGrid is resolved 418-419. It is honestly what I need the most as I can improve it's fidelity from other sources.

Relationship has a particularly garbage implementation from keen, but maybe do a fallback ?
`using (List<long>.Enumerator enumerator = BigOwners.GetEnumerator())
{
	while (enumerator.MoveNext())
	{
		switch (MyIDModule.GetRelationPlayerPlayer(enumerator.Current, player))
		{
		case MyRelationsBetweenPlayers.Self:
			return true;
		case MyRelationsBetweenPlayers.Allies:
			return true;
		}
	}
}
return false;
`
I'm sympathetic on that one. All the ownership is per block not per grid. That a higher level ownership isn't well maintained on the cubegrid level is bullshit.

**Comment by sstixrud** [comment] 2022-10-22 00:55
That will fail in situations where you pass in a shooter whose AI does not have that the supplied target as valid.  Likely because its out of range of the weapons on that grid/subgrid.  If you have multiple subgrids then be sure to use a shooter from the grid with a weapon with the most range.  It could also be that u have cached an entity ID that was valid but is no longer so.

**Comment by keleios** [comment] 2022-10-24 17:06
So I took what you said and had my QA do some additional testing. Got a bit more information.
Apparently in this case the WC AI for the ship got stuck on a subgrid that had a CTC without weapons (camera on a turret assembly).

I will try and get a blueprint and a script that reproduces the issue reliably.

**Comment by sstixrud** [comment] 2022-10-25 00:54
This is expected behavior.  WC's AI does not "move" nor get "stuck" on a subgrid.  Instead what happens is every grid, subgrid or no, has its own WC AI which manages the weapons that are on that grid and only those weapons.  Each subgrid in affect has its own target list that is only as good as the weapons on it.

**Comment by keleios** [comment] 2022-10-25 04:48
I'll dig into it more this weekend, but I'm pretty sure it isn't a bug with my script. I'm just doing the typical initialization flow by activating the WcAPI using the Programmable Block located on the primary grid during script construction. When I call GetSortedThreats I again use that same reference. I just checked to be sure. 

The only reason I brought up AIs at all was from analysis of GetDetailedEntityInfo and what must have happened to get to that state. You know more about the code base than I do as the author, but in regards to 'each grid having its own AI' might be undermined by the call at the top of GetDetailedEntityInfo that seeks elsewhere in the heirarchy in shooter.GetTopMostParent() as MyCubeGrid ? If for some reason the CTC grid was considered the TopMostParent it could cause this issue?

**Comment by sstixrud** [comment] 2022-10-25 07:55
private void PbGetSortedThreats(object arg1, object arg2)
calls
private void GetSortedThreats(IMyEntity shooter, ICollection<MyTuple<IMyEntity, float>> collection)

which does

            var grid = shooter.GetTopMostParent() as MyCubeGrid;
            Ai ai;
            if (grid != null && _session.EntityAIs.TryGetValue(grid, out ai))

EntityAIs will return whatever AI is assigned to shooter.GetTopMostParent() as MyCubeGrid, which AI it returns depends on which shooter you pass it.  If you pass it a grid or block on a CTC turret then that is the AI u will get.

The issue I think you are running into is that target list is then sorted and details populated by the master AI, which is whichever grid is has the highest EntityId.  I'll change this in the next update to not use the master AI but whichever shooter u passed it.

**Comment by sstixrud** [comment] 2022-10-26 05:25
MyDetectedEntityInfo has been improved on git, will go live with the next update.  Note that other methods like getsortedTargets still only pulls from the shooter's grid AI, not all Ais on grid.  When asking for a list of targets it is still grid specific, so if your script is also managing subgrid weapons be sure to use that grid for weapon actions and target lists.

**Closed by sstixrud** 2022-10-26 05:25 UTC
