### ISSUE TITLE
(Bug) Weapons stop working mid fight

### ISSUE THREAD

**Issue by fastidious-ghoul** [sstixrud/WeaponCore#162] opened 2020-05-25 07:40 UTC
## Is this a multiplayer or singleplayer bug?
Singleplayer

## Describe the bug:
After awhile in combat, weapons will stop working. Ships will idle next to each other, not firing,  etc

## Steps To Reproduce:
Launch game, get in a few fights, eventually weapons stop working. I can't pinpoint how long this takes.

## Expected behavior:
Weapons keep working

### (Optional) Additional content/log files/etc:

I found this in the debug, maybe it helps:
```
05-25-20_00-33-40-925 - Exception in SessionBeforeSim: System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.Support.RunAv.RunHitSounds()
   at WeaponCore.Support.RunAv.End()
   at WeaponCore.Session.UpdateBeforeSimulation()
05-25-20_00-33-40-944 - Exception in SessionBeforeSim: System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.Support.RunAv.RunHitSounds()
   at WeaponCore.Support.RunAv.End()
   at WeaponCore.Session.UpdateBeforeSimulation()
05-25-20_00-33-40-958 - Exception in SessionBeforeSim: System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.Support.RunAv.RunHitSounds()
   at WeaponCore.Support.RunAv.End()
   at WeaponCore.Session.UpdateBeforeSimulation()
05-25-20_00-33-40-976 - Exception in SessionBeforeSim: System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.Support.RunAv.RunHitSounds()
   at WeaponCore.Support.RunAv.End()
   at WeaponCore.Session.UpdateBeforeSimulation()

```

**Comment by TheWizardLizard** [comment] 2020-05-25 08:20
Please remember to add a title to your issues in the future

**Comment by fastidious-ghoul** [comment] 2020-05-26 19:49
Found an exception that appears before this one does.
```
   at WeaponCore.Projectiles.Projectile.StaticEntCheck() AiNull:False - StaticsNull:False - FiringCubeNull:False - AmmoNull:False) - False 
05-26-20_12-07-23-378 - Exception in StaticEntCheck: System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.Projectiles.Projectile.StaticEntCheck() AiNull:False - StaticsNull:False - FiringCubeNull:False - AmmoNull:False) - False 
05-26-20_12-07-23-390 - Exception in StaticEntCheck: System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.Projectiles.Projectile.StaticEntCheck() AiNull:False - StaticsNull:False - FiringCubeNull:False - AmmoNull:False) - False 
05-26-20_12-07-23-406 - Exception in StaticEntCheck: System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.Projectiles.Projectile.StaticEntCheck() AiNull:False - StaticsNull:False - FiringCubeNull:False - AmmoNull:False) - False 
05-26-20_12-07-23-424 - Exception in StaticEntCheck: System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.Projectiles.Projectile.StaticEntCheck() AiNull:False - StaticsNull:False - FiringCubeNull:False - AmmoNull:False) - False 
05-26-20_12-07-23-440 - Exception in StaticEntCheck: System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.Projectiles.Projectile.StaticEntCheck() AiNull:False - StaticsNull:False - FiringCubeNull:False - AmmoNull:False) - False 
05-26-20_12-07-23-458 - Exception in StaticEntCheck: System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.Projectiles.Projectile.StaticEntCheck() AiNull:False - StaticsNull:False - FiringCubeNull:False - AmmoNull:False) - False 
05-26-20_12-07-23-475 - Exception in StaticEntCheck: System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.Projectiles.Projectile.StaticEntCheck() AiNull:False - StaticsNull:False - FiringCubeNull:False - AmmoNull:False) - False 
05-26-20_12-07-23-497 - Exception in StaticEntCheck: System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.Projectiles.Projectile.StaticEntCheck() AiNull:False - StaticsNull:False - FiringCubeNull:False - AmmoNull:False) - False 
05-26-20_12-07-23-509 - Exception in StaticEntCheck: System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.Projectiles.Projectile.StaticEntCheck() AiNull:False - StaticsNull:False - FiringCubeNull:False - AmmoNull:False) - False 
05-26-20_12-07-23-524 - Exception in StaticEntCheck: System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.Projectiles.Projectile.StaticEntCheck() AiNull:False - StaticsNull:False - FiringCubeNull:False - AmmoNull:False) - False 
05-26-20_12-07-23-541 - Exception in StaticEntCheck: System.NullReferenceException: Object reference not set to an instance of an object.
```

**Comment by sstixrud** [comment] 2020-05-28 05:10
@fastidious-ghoul what weapons are you using.  I am not able to reproduce.  Also please clear out your mod caches.

**Comment by sstixrud** [comment] 2020-05-28 05:20
Also please include the entire log file

**Comment by fastidious-ghoul** [comment] 2020-05-28 18:49
05-28-20_11-30-40-053 - Logging Started
05-28-20_11-30-40-145 - largeCollisionSize: 5
05-28-20_11-30-40-147 - largeCollisionSize: 5
05-28-20_11-30-40-148 - largeCollisionSize: 10
05-28-20_11-30-40-254 - largeCollisionSize: 5
05-28-20_11-31-08-529 - changing power block
05-28-20_11-31-08-538 - changing power block
05-28-20_11-31-08-538 - changing power block
05-28-20_11-31-08-540 - changing power block
05-28-20_11-31-08-540 - changing power block
05-28-20_11-31-08-541 - changing power block
05-28-20_11-31-08-549 - changing power block
05-28-20_11-31-08-549 - changing power block
05-28-20_11-31-08-551 - changing power block
05-28-20_11-31-08-551 - changing power block
05-28-20_11-31-08-551 - changing power block
05-28-20_11-31-08-551 - changing power block
05-28-20_11-31-08-551 - changing power block
05-28-20_11-31-08-552 - changing power block
05-28-20_11-31-08-554 - changing power block
05-28-20_11-31-08-554 - changing power block
05-28-20_11-31-08-554 - changing power block
05-28-20_11-31-08-556 - changing power block
05-28-20_11-31-08-563 - changing power block
05-28-20_11-31-08-570 - changing power block
05-28-20_11-31-08-578 - changing power block
05-28-20_11-31-08-579 - changing power block
05-28-20_11-31-08-579 - changing power block
05-28-20_11-31-08-580 - changing power block
05-28-20_11-31-08-581 - changing power block
05-28-20_11-31-08-581 - changing power block
05-28-20_11-31-08-582 - changing power block
05-28-20_11-31-08-583 - changing power block
05-28-20_11-31-08-583 - changing power block
05-28-20_11-31-08-583 - changing power block
05-28-20_11-31-08-583 - changing power block
05-28-20_11-31-08-583 - changing power block
05-28-20_11-31-08-583 - changing power block
05-28-20_11-31-08-583 - changing power block
05-28-20_11-31-08-583 - changing power block
05-28-20_11-31-08-583 - changing power block

This is the rest of the logfile before the failure, it floods the logfile with tens of thousands of lines of the other stuff, so I can't really post it here.

I'm using both the MWI packs, homing weaponry, Paragon beam cannon, GAU and beam sword, MA weaponcore weapons

I removed the vanilla weapon replacement mod as someone else suggested it would fix, no change. I'm always able to shoot for a short time before everything stops.

**Comment by sstixrud** [comment] 2020-05-29 01:43
@fastidious-ghoul so the issue no longer happens after removing vanilla replacement and deleting the blocks?  So its fixed at this point?

**Comment by fastidious-ghoul** [comment] 2020-05-29 03:09
No, sorry, to be clear, the vanilla gatling turret still fires even when WeaponCore weapons fail if vanilla replacement is removed.

**Comment by sstixrud** [comment] 2020-05-31 20:18
Should be fixed now.

**Closed by sstixrud** 2020-05-31 20:18 UTC
Labels: Housecleaning (Bug)
